FROM node:18-alpine
ARG MONGODB_SRV
ENV MONGODB_SRV=$MONGODB_SRV

ARG GOOGLE_CLOUD_BUCKET
ENV GOOGLE_CLOUD_BUCKET=$GOOGLE_CLOUD_BUCKET

COPY . .

RUN npm install 
RUN npx tsc --project ./

EXPOSE 8080

CMD [ "node", "dist/server.js" ]
